<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MediCore.Worker-53526de2-9adb-406d-acba-ba229aba0947</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\MediCore.Business.csproj" />
    <ProjectReference Include="..\DataAccess\MediCore.DataAccess.csproj" />
    <ProjectReference Include="..\Models\MediCore.Models.csproj" />
    <ProjectReference Include="..\Common\MediCore.Common.csproj" />
  </ItemGroup>
</Project>
