import type { UserRole } from '@/mocks/users';

export type RoutePath = string;

// Routes each role can access
export const roleRoutes: Record<UserRole, string[]> = {
  admin: [
    '/app/hl7-fhir',
    '/app/dashboard',
    '/app/reportes',
    '/app/agenda',
    '/app/sala-espera',
    '/app/monitor-turnos',
    '/app/triage',
    '/app/urgencias',
    '/app/pacientes',
    '/app/pacientes/nuevo',
    '/app/pacientes/',
    '/app/consultas',
    '/app/recetas',
    '/app/estudios',
    '/app/farmacia',
    '/app/caja',
    '/app/caja/cortes',
    '/app/facturacion',
    '/app/administracion/usuarios',
    '/app/administracion/medicos',
    '/app/administracion/especialidades',
    '/app/administracion/sucursales',
    '/app/administracion/servicios',
    '/app/administracion/catalogos',
    '/app/seguridad/roles',
    '/app/seguridad/auditoria',
    '/app/normatividad/',
  ],
  medico: [
    '/app/dashboard',
    '/app/agenda',
    '/app/sala-espera',
    '/app/monitor-turnos',
    '/app/triage',
    '/app/urgencias',
    '/app/pacientes',
    '/app/pacientes/nuevo',
    '/app/pacientes/',
    '/app/consultas',
    '/app/recetas',
    '/app/estudios',
    '/app/farmacia',
    '/app/normatividad/consentimientos',
    '/app/normatividad/referencias',
    '/app/normatividad/egresos',
    '/app/normatividad/notas-enfermeria',
    '/app/normatividad/vigilancia',
    '/app/normatividad/profesionales',
  ],
  recepcion: [
    '/app/dashboard',
    '/app/agenda',
    '/app/sala-espera',
    '/app/monitor-turnos',
    '/app/triage',
    '/app/pacientes',
    '/app/pacientes/nuevo',
    '/app/pacientes/',
    '/app/caja',
    '/app/caja/cortes',
  ],
  enfermeria: [
    '/app/dashboard',
    '/app/sala-espera',
    '/app/monitor-turnos',
    '/app/triage',
    '/app/urgencias',
    '/app/pacientes',
    '/app/pacientes/',
    '/app/normatividad/notas-enfermeria',
    '/app/normatividad/consentimientos',
    '/app/normatividad/profesionales',
  ],
  caja: [
    '/app/dashboard',
    '/app/caja',
    '/app/caja/cortes',
    '/app/facturacion',
    '/app/pacientes',
    '/app/pacientes/',
    '/app/farmacia',
    '/app/recetas',
    '/app/estudios',
  ],
  farmacia: [
    '/app/dashboard',
    '/app/farmacia',
    '/app/recetas',
    '/app/estudios',
    '/app/pacientes',
    '/app/pacientes/',
  ],
  laboratorio: [
    '/app/dashboard',
    '/app/estudios',
    '/app/recetas',
    '/app/pacientes',
    '/app/pacientes/',
  ],
  directivo: [
    '/app/hl7-fhir',
    '/app/dashboard',
    '/app/reportes',
    '/app/agenda',
    '/app/sala-espera',
    '/app/monitor-turnos',
    '/app/triage',
    '/app/urgencias',
    '/app/pacientes',
    '/app/pacientes/',
    '/app/consultas',
    '/app/recetas',
    '/app/estudios',
    '/app/farmacia',
    '/app/caja',
    '/app/caja/cortes',
    '/app/facturacion',
    '/app/administracion/usuarios',
    '/app/administracion/medicos',
    '/app/administracion/especialidades',
    '/app/administracion/sucursales',
    '/app/administracion/servicios',
    '/app/administracion/catalogos',
    '/app/seguridad/roles',
    '/app/seguridad/auditoria',
    '/app/normatividad/',
  ],
};

export function canAccessRoute(role: UserRole | null, path: string): boolean {
  if (!role) return false;
  const routes = roleRoutes[role];
  return routes.some((r) => {
    if (r.endsWith('/')) {
      return path.startsWith(r);
    }
    return path === r || path.startsWith(`${r}/`);
  });
}

// Feature-level permissions for UI controls
export const rolePermissions: Record<UserRole, {
  canCreatePatient: boolean;
  canEditPatient: boolean;
  canDeletePatient: boolean;
  canCreateConsulta: boolean;
  canEditConsulta: boolean;
  canCreateReceta: boolean;
  canDispensar: boolean;
  canCobrar: boolean;
  canCerrarCaja: boolean;
  canAdminUsers: boolean;
  canAdminMedicos: boolean;
  canAdminCatalogos: boolean;
  canVerAuditoria: boolean;
  canEditTriage: boolean;
  canAtenderUrgencia: boolean;
  canVerEstadisticas: boolean;
  canExportar: boolean;
}> = {
  admin: {
    canCreatePatient: true,
    canEditPatient: true,
    canDeletePatient: true,
    canCreateConsulta: true,
    canEditConsulta: true,
    canCreateReceta: true,
    canDispensar: true,
    canCobrar: true,
    canCerrarCaja: true,
    canAdminUsers: true,
    canAdminMedicos: true,
    canAdminCatalogos: true,
    canVerAuditoria: true,
    canEditTriage: true,
    canAtenderUrgencia: true,
    canVerEstadisticas: true,
    canExportar: true,
  },
  medico: {
    canCreatePatient: true,
    canEditPatient: true,
    canDeletePatient: false,
    canCreateConsulta: true,
    canEditConsulta: true,
    canCreateReceta: true,
    canDispensar: false,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: true,
    canAtenderUrgencia: true,
    canVerEstadisticas: false,
    canExportar: true,
  },
  recepcion: {
    canCreatePatient: true,
    canEditPatient: true,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: false,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: false,
    canAtenderUrgencia: false,
    canVerEstadisticas: false,
    canExportar: false,
  },
  enfermeria: {
    canCreatePatient: false,
    canEditPatient: false,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: false,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: true,
    canAtenderUrgencia: false,
    canVerEstadisticas: false,
    canExportar: false,
  },
  caja: {
    canCreatePatient: false,
    canEditPatient: false,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: false,
    canCobrar: true,
    canCerrarCaja: true,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: false,
    canAtenderUrgencia: false,
    canVerEstadisticas: false,
    canExportar: true,
  },
  farmacia: {
    canCreatePatient: false,
    canEditPatient: false,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: true,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: false,
    canAtenderUrgencia: false,
    canVerEstadisticas: false,
    canExportar: false,
  },
  laboratorio: {
    canCreatePatient: false,
    canEditPatient: false,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: false,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: false,
    canAdminMedicos: false,
    canAdminCatalogos: false,
    canVerAuditoria: false,
    canEditTriage: false,
    canAtenderUrgencia: false,
    canVerEstadisticas: false,
    canExportar: false,
  },
  directivo: {
    canCreatePatient: false,
    canEditPatient: false,
    canDeletePatient: false,
    canCreateConsulta: false,
    canEditConsulta: false,
    canCreateReceta: false,
    canDispensar: false,
    canCobrar: false,
    canCerrarCaja: false,
    canAdminUsers: true,
    canAdminMedicos: true,
    canAdminCatalogos: true,
    canVerAuditoria: true,
    canEditTriage: false,
    canAtenderUrgencia: false,
    canVerEstadisticas: true,
    canExportar: true,
  },
};

export function getPermissions(role: UserRole | null) {
  if (!role) {
    return {
      canCreatePatient: false,
      canEditPatient: false,
      canDeletePatient: false,
      canCreateConsulta: false,
      canEditConsulta: false,
      canCreateReceta: false,
      canDispensar: false,
      canCobrar: false,
      canCerrarCaja: false,
      canAdminUsers: false,
      canAdminMedicos: false,
      canAdminCatalogos: false,
      canVerAuditoria: false,
      canEditTriage: false,
      canAtenderUrgencia: false,
      canVerEstadisticas: false,
      canExportar: false,
    };
  }
  return rolePermissions[role];
}